{
 "title": "Geohash SSH",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "SSH Attacks Location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "geohash" ], "type": "tag" }
     ],
     "measurement": "geossh",
     "query": "SELECT sum( \"value\") as value FROM \"geossh\" GROUP BY \"location\", \"ip\", \"geohash\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed SSH Attempts",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "username" ], "type": "tag" },
      { "params": [ "geohash" ], "type": "tag" }
     ],
     "measurement": "geossh",
     "query": "SELECT sum( \"value\") FROM \"geossh\" WHERE $timeFilter GROUP BY \"country\", \"ip\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last( \"value\") FROM \"geossh\" WHERE $timeFilter GROUP BY \"country\", \"ip\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SSH Attacks by IP and Country",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_country: $tag_ip",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "geossh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Most popular usernames",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_username",
     "groupBy": [
      { "params": [ "username" ], "type": "tag" }
     ],
     "measurement": "geossh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Most popular attackers",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "country" ], "type": "tag" }
     ],
     "measurement": "geossh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}